[tool.poetry]
name = "MasterThesis"
version = "0.1.0"
description = ""
authors = ["omarcastano <omar.castano@udea.edu.co>"]

[tool.poetry.dependencies]
python = "^3.7.13"
geopandas = "^0.10.2"

[tool.poetry.dev-dependencies]
GDAL = "3.3.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
