[tool.poetry]
name = "masterthesis"
version = "0.1.0"
description = "This is my Master Theses project"
authors = ["omarcastano <omar.castano@udea.edu.co>"]
packages = [
    {include = "MasterThesis"}
]

[tool.poetry.dependencies]
python = ">=3.7.13, <=3.9"
GDAL = "3.3.0"

[tool.poetry.dev-dependencies]
jupyterlab = "^3.4.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
